Application.Web/Models/ViewModels/ExpectedReceiptViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Application.Web.Models.ViewModels
{
    public class ExpectedReceiptViewModel
    {
        [Table("ExpectedReceipts")]
        public class ExpectedReceipt
        {
            [Key]
            public long? Id { get; set; }

            public bool IsActive { get; set; }

            [DataType(DataType.Date)]
            [Required(ErrorMessage = "Expected Receipt Date is required")]
            [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
            [Display(Name = "Expected Receipt Date")]
            public DateTime ExpectedReceiptDate { get; set; }

            public DateTime? DateCreated { get; set; }

            [Required(ErrorMessage = "Goods Received Number is required")]
            [Display(Name = "Goods Received Number")]
            public string GoodsReceivedNumber { get; set; }

            [Required(ErrorMessage = "Reference Number is required")]
            [RegularExpression(@"[a-zA-Z0-9-//()-,.]+$", ErrorMessage = "Invalid Reference Number. It allows input Alphanumeric and , . / ( ) - * + only")]
            [Display(Name = "Reference Number")]
            public string ReferenceNumber { get; set; }

            [Display(Name = "Reference Number")]
            public string AutoReferenceNumber { get; set; }

            [Required(ErrorMessage = "Received is required")]
            [Display(Name = "Received")]
            public bool Received { get; set; }

            [Display(Name = "Comments")]
            public string Comments { get; set; }

            [Display(Name = "Warehouse Address")]
            public string Address { get; set; }

            [Required(ErrorMessage = "Warehouse is required")]
            [Display(Name = "Warehouse")]
            public string WarehouseCode { get; set; }

            [Display(Name = "Warehouse Description")]
            public string WarehouseDescription { get; set; }

            [Display(Name = "Received By")]
            public string ReceivedBy { get; set; }

            [DataType(DataType.Date)]
            [Required(ErrorMessage = "Received Date is required")]
            [DisplayFormat(DataFormatString = "{0:dd MMM yyyy}")]
            [Display(Name = "Received Date")]
            public DateTime? ReceivedDate { get; set; }

            [Display(Name = "Vendor/Supplier")]
            [RegularExpression(@"[a-zA-Z0-9- //()-,.]+$", ErrorMessage = "Invalid Supplier. It allows input Alphanumeric and , . / ( ) - * + only")]
            public string Supplier { get; set; }

            [Display(Name = "Supplier")]
            public long? VendorId { get; set; }

            [Display(Name = "Haulier Name")]
            public string HaulierName { get; set; }

            [Display(Name = "Haulier Code")]
            public string HaulierCode { get; set; }

            public long? CustomerId { get; set; }

            [Required(ErrorMessage = "Transaction Status is required")]
            public long? StatusId { get; set; }

            public long? HaulierId { get; set; }

            public long? CustomerClientId { get; set; }

            //public int WarehouseId { get; set; }

            [Required(ErrorMessage = "Transaction Status is required")]
            [Display(Name = "Transaction Status")]
            public string StatusCode { get; set; }

            [Display(Name = "Is Planned?")]
            public bool Planned { get; set; }

            public string CreatedBy { get; set; }

            public string UpdatedBy { get; set; }

            public bool IsProcessing { get; set; }
        }

        [Table("ExpectedReceiptLines")]
        public class ExpectedReceiptLine
        {
            [Key]
            public long Id { get; set; }

            public int? CustomerId { get; set; }

            public bool IsActive { get; set; }

            public bool IsItemExist { get; set; }

            public long ExpectedReceiptId { get; set; }

            [Display(Name = "Batch")]
            public string Batch { get; set; }

            [Required]
            public long? ProductId { get; set; }

            [Required]
            public long? UomId { get; set; }

            [Required]
            public long? ItemId { get; set; }

            public long StatusId { get; set; }

            [Required(ErrorMessage = "Line is required")]
            [Display(Name = "Line")]
            public int Line { get; set; }

            [Required(ErrorMessage = "Product Code is required")]
            [Display(Name = "Item Group")]
            public string ProductCode { get; set; }

            [Required(ErrorMessage = "Item Description is required")]
            [Display(Name = "Item Description")]
            public string ItemDescription { get; set; }

            [Required(ErrorMessage = "Item Code is required")]
            [Display(Name = "Item Code")]
            public string ItemCode { get; set; }

            public string BrandCode { get; set; }

            public string Brand { get; set; }

            public long? BrandId { get; set; }

            [Required(ErrorMessage = "Brand is required")]
            [Display(Name = "Brand")]
            public string BrandName { get; set; }

            [Display(Name = "Expiry Date")]
            public DateTime? ExpiryDate { get; set; }

            [Range(1, Int32.MaxValue, ErrorMessage = "Value should be greater than or equal to 1")]
            [Required(ErrorMessage = "Quantity is required")]
            [Display(Name = "Quantity")]
            public int Quantity { get; set; }

            [Required(ErrorMessage = "Uom is required")]
            [Display(Name = "Uom")]
            public string UomDescription { get; set; }

            public string ReferenceNumber { get; set; }

            public string GoodsReceivedNumber { get; set; }

            public bool IsChecked { get; set; }

            public string StatusCode { get; set; }

            public string CreatedBy { get; set; }

            public string UpdatedBy { get; set; }

            public DateTime? DateCreated { get; set; }

            public DateTime? DateUpdated { get; set; }

        }
    }
}

Application.Web/Controllers/SelectListController.cs
using Application.Web.Helper;
using Application.Web.Models.ViewModels;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Http.Results;
using System.Web.Mvc;


namespace Application.Web.Controllers
{
    public class SelectListController : BaseController
    {
         private int _customerId = int.Parse(CookieHelper.CustomerId);

        //[HttpPost]
        //public async Task<JsonResult> Role(string term)
        //{
        //    var listOfRoles = new List<dynamic>{
        //        new { id = "Administrator", text = "Administrator" },
        //        new { id = "SuperAdmin", text = "SuperAdmin" },
        //        new { id = "WarehouseManager", text = "Warehouse Manager" },
        //        new { id = "WarehouseOperatives", text = "Warehouse Operatives" },
        //        new { id = "WarehouseSupervisor", text = "Warehouse Supervisor" },
        //        new { id = "WarehouseAdministrator", text = "Warehouse Administrator" },
        //        new { id = "Warehouse Staff", text = "Warehouse Staff" },

        //    }.AsEnumerable();

        //    if (!string.IsNullOrEmpty(term))
        //    {
        //        listOfRoles = listOfRoles.Where(x => x.text.ToLower().Contains(term.ToLower()));
        //    }

        //    return Json(listOfRoles);
        //}

        [HttpPost]
        public async Task<JsonResult> IsActiveSelectList(string term)
        {
            var list = new List<dynamic>{
                new { id = "true", text = "Yes" },
                new { id = "false", text = "No" },
            }.AsEnumerable();

            if (!string.IsNullOrEmpty(term))
            {
                list = list.Where(x => x.text.ToLower().Contains(term.ToLower()));
            }

            return Json(list);            
        }

        [HttpPost]
        public async Task<JsonResult> StatusSelectList(string term)
        {

            var list = new List<dynamic>{
                new { id = "ALL", text = "ALL" },
                new { id = "For Receiving", text = "For Receiving" },
                new { id = "Received", text = "Received" },
                new { id = "Completed", text = "Completed" }

            }.AsEnumerable();

            if (!string.IsNullOrEmpty(term))
            {
                list = list.Where(x => x.text.ToLower().Contains(term.ToLower()));
            }
            return Json(list);
        }

        [HttpPost]
        public async Task<JsonResult> StatusSelectListForReceipt(string term)
        {

            var list = new List<dynamic>{
                new { id = "ALL", text = "ALL" },
                new { id = "Received", text = "Received" },
                new { id = "Completed", text = "Completed" }

            }.AsEnumerable();

            if (!string.IsNullOrEmpty(term))
            {
                list = list.Where(x => x.text.ToLower().Contains(term.ToLower()));
            }
            return Json(list);
        }

        [HttpPost]
        public async Task<JsonResult> StatusSelectListForDeliveryRequest(string term)
        {
            var list = new List<StatusViewModel>();

            var url = $"api/Status/GetList/{true}/{_customerId}";
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {
                var result = response.Content;
                var obj = JsonConvert.DeserializeObject<List<StatusViewModel>>(result);
                list = obj;

                var status = new List<dynamic> { new { id = 0, text = "ALL"} };
                    
                status.AddRange(list.Where(x => (x.Name?.ToLower().Contains(term.ToLower()) ?? false)
                                                && (x.Id == 13 || x.Id == 14 || x.Id == 15))
                    .Select(x => new
                    {
                        id = x.Id,
                        text = x.Name

                    }));


                return Json(status);
            }
            return null;
        }

        [HttpPost]
        public async Task<JsonResult> CustomerClientList(string term)
        {
            var list = new List<CustomerClientViewModel>();
            var url = $"api/customerclient/getlist/{true}/{_customerId}";
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {
                var result = response.Content;
                list = JsonConvert.DeserializeObject<List<CustomerClientViewModel>>(result);

                return Json(list.Where(x => x.Name?.ToLower().Contains(term.ToLower()) ?? false)
                    .Select(x => new
                    {
                        id = x.Id,
                        text = x.Name

                    }).ToList());
            }
            return null;
        }

        [HttpPost]
        public async Task<JsonResult> VendorList(string term)
        {
            var list = new List<VendorViewModel>();
            var url = $"api/Vendor/GetList/{true}/{_customerId}";
            var response = await HttpClientHelper.ApiCall(url, Method.GET);
            //term = "";

            if (response.IsSuccessful)
            {
                var result = response.Content;
                list = JsonConvert.DeserializeObject<List<VendorViewModel>>(result);

                var warehouse = list.Where(x => (x.VendorName?.ToLower().Contains(term.ToLower()) ?? false))
                    .Select(x => new
                    {
                        id = x.VendorCode,
                        text = x.VendorName

                    }).ToList();

                return Json(warehouse);
            }
            return null;
        }

        [HttpPost]
        public async Task<JsonResult> VendorIdList(string term)
        {
            var list = new List<VendorViewModel>();
            var url = $"api/Vendor/GetList/{true}/{_customerId}";
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {
                var result = response.Content;
                var obj = JsonConvert.DeserializeObject<List<VendorViewModel>>(result);
                list = obj;

                var warehouse = list.Where(x => (x.VendorName?.ToLower().Contains(term.ToLower()) ?? false))
                    .Select(x => new
                    {
                        id = x.Id,
                        text = x.VendorName

                    }).ToList();

                return Json(warehouse);
            }
            return null;
        }

        [HttpPost]
        public async Task<JsonResult> WarehouseList(string term)
        {
            var list = new List<WarehouseViewModel>();
            var url = $"api/Warehouse/GetList/{true}/{_customerId}";
            var response = await HttpClientHelper.ApiCall(url, Method.GET);
            //term = "";

            if (response.IsSuccessful)
            {
                var result = response.Content;
                list = JsonConvert.DeserializeObject<List<WarehouseViewModel>>(result);

                var warehouse = list.Where(x => (x.Description?.ToLower().Contains(term.ToLower()) ?? false))
                    .Select(x => new
                    {
                        id = x.WarehouseCode,
                        text = x.Description,
                        otherField = x.Address1 ?? "Sample City"

                    }).ToList();

                return Json(warehouse);
            }
            return null;
        }

        [HttpPost]
        public async Task<JsonResult> WarehouseIdList(string term)
        {
            var list = new List<WarehouseViewModel>();
            var url = $"api/Warehouse/GetList/{true}/{_customerId}";
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {
                var result = response.Content;
                var obj = JsonConvert.DeserializeObject<List<WarehouseViewModel>>(result);
                list = obj;

                var warehouse = list.Where(x => (x.Description?.ToLower().Contains(term.ToLower()) ?? false))
                    .Select(x => new
                    {
                        id = x.Id,
                        text = x.Description,
                        otherField = x.Address1 ?? "Sample City"

                    }).ToList();

                return Json(warehouse);
            }
            return null;
        }

        [HttpPost]
        public async Task<JsonResult> LocationList(string term)
        {
            var list = new List<LocationViewModel>();
            var url = $"api/Location/GetList/{true}/{_customerId}";
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {
                var result = response.Content;
                var obj = JsonConvert.DeserializeObject<List<LocationViewModel>>(result);
                list = obj;
            }

            return Json(list);
        }

        [HttpPost]
        public async Task<JsonResult> LocationListByWarehouseCode(string term, string code)
        {
            if (!string.IsNullOrEmpty(code))
            {
                var list = new List<LocationViewModel>();
                var url = $"api/Location/GetByWarehouseCode/{code}/{true}/{_customerId}";

                var response = await HttpClientHelper.ApiCall(url, Method.GET);

                if (response.IsSuccessful)
                {
                    var result = response.Content;
                    var obj = JsonConvert.DeserializeObject<List<dynamic>>(result);

                    list = obj.Select(x => new LocationViewModel
                    {
                        Id = x.Id,
                        LocationCode = x.Code,

Application.Web/Views/ExpectedReceipt/Create.cshtml
@model Application.Web.Models.ViewModels.ExpectedReceiptViewModel.ExpectedReceipt
@{
    ViewBag.Title = "Expected Receipt Create";
}

<style type="text/css">
    hr.style5 {
        background-color: #fff;
        border-top: 2px dashed #8c8b8b;
    }

    .shadow-textarea textarea.form-control::placeholder {
        font-weight: 300;
    }

    .shadow-textarea textarea.form-control {
        padding-left: 0.8rem;
    }

    .select2-container {
        width: 100% !important;
    }

    input, optgroup, select, textarea {
        margin: 5px;
    }
</style>

<div id="form-container" data-url="@Url.Action("Create","ExpectedReceipt")">
    @using (Html.BeginForm("Create", "ExpectedReceipt", FormMethod.Post, new { id = "create-form", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.GoodsReceivedNumber)
        @Html.HiddenFor(model => model.AutoReferenceNumber)
        @Html.HiddenFor(model => model.CustomerId)
        @Html.HiddenFor(model => model.Supplier)

         <!-- Horizontal Form -->
        <div class="box-body">
            <div class="form-horizontal">
                <div class="col-md-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.ReferenceNumber, new { @class = "control-label col-md-15 required" })
                            @Html.EditorFor(model => model.ReferenceNumber, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.ReferenceNumber, "", new { @class = "text-danger" })
                            <input onclick="return change(this)" type="button" value="Input Reference Number" name="button1" id="disablebutton">
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.ExpectedReceiptDate, new { @class = "control-label col-md-15 required" })
                            @Html.TextBox("ExpectedReceiptDate", DateTime.Now, "{0:yyyy-MM-dd}", new { @class = "form-control", @type = "date", min = DateTime.Now.ToString("yyyy-MM-dd") })
                            @Html.ValidationMessageFor(model => model.ExpectedReceiptDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.Supplier, new { @class = "control-label" })
                            <select class="form-control" id="VendorId" name="VendorId"></select>
                            @*@Html.EditorFor(model => model.Supplier, new { htmlAttributes = new { @class = "form-control" } })*@
                            @Html.ValidationMessageFor(model => model.Supplier, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-6">
                            @Html.LabelFor(model => model.HaulierId, "Haulier", new { @class = "control-label" })
                            <select class="form-control" id="HaulierId" name="HaulierId"></select>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.WarehouseCode, "Warehouse", new { @class = "control-label required" })
                            <select class="form-control" id="WarehouseCode" name="WarehouseCode" required></select>
                            @Html.ValidationMessageFor(model => model.WarehouseCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-15" })
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group shadow-textarea">
                        @Html.LabelFor(model => model.Comments, new { @class = "control-label col-md-3" })
                        <div class="col-md-12">
                            <textarea class="form-control z-depth-1" id="Comments" name="Comments" rows="3" placeholder="Write something here..."></textarea>
                            @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="box-footer">
            <input type="submit" id="create-submit" value="Save" class="btn btn-primary pull-right" />
        </div>
    }
</div>

<link href="~/Content/css-select2/select2.css" rel="stylesheet" />
<script src="~/Content/js-select2/select2.js"></script>
@*<script type="text/javascript" src="~/Scripts/CustomSelectList.js"></script>*@

<script type="text/javascript">
    var refnum = $('#ReferenceNumber').val();

    function change(el)
    {
        debugger;
        if (el.value === "Input Reference Number")
            el.value = "Generate Reference Number";
        else
            el.value = "Input Reference Number";
    }

    $('#disablebutton').click(function () {
        debugger;
        if ($('#ReferenceNumber').prop('readonly'))
        {
            $('#ReferenceNumber').removeAttr('readonly');
            $('#ReferenceNumber').val("");
        }
        else
        {
            $('#ReferenceNumber').attr('readonly', 'readonly');
            $('#ReferenceNumber').val(refnum);

            $('#validationSum').text("");
        }
    });

    //Select2
    var vendorSelectList = new CustomSelectList(['#VendorId', '@Url.Action("VendorIdList", "SelectList")', 'Search Supplier']);
    vendorSelectList.init();
    $('#VendorId').on('select2:select', function (e) {
        debugger;
        var data = $(e.currentTarget).select2('data')[0];
        $('#Supplier').val(data.text);
    });

    var warehouseSelectList = new CustomSelectList(['#WarehouseCode', '@Url.Action("WarehouseList", "SelectList")', 'Search Warehouse']);
    warehouseSelectList.init();

    $('#WarehouseCode').on('select2:select', function (e) {
        debugger;
        var data = $(e.currentTarget).select2('data')[0];
        $('#Address').val(data.otherField)
    });

    var haulierSelectList = new CustomSelectList(['#HaulierId', '@Url.Action("HaulierList", "SelectList")', 'Search Haulier']);
    haulierSelectList.init();

    $('#ReferenceNumber').change(function () {
        debugger;
        var referenceNumber = $("#ReferenceNumber").val();
        var customerId = $("#CustomerId").val();

        $.ajax({
            url: '@Url.Action("ValidateReferenceNumber", "ExpectedReceipt")' + "?referenceNumber=" + referenceNumber + "&customerId=" + customerId,
             method: "POST",
            datatype: "json",
            contentType: "application/json",
            success: function (data) {
                //$('.field-validation-error').remove(data.message);
                debugger;
                if (data.message == "Reference Number is already taken.") {
                    $('#validationSum').remove();
                    $('#ReferenceNumber').parent().append('<span class="text-danger field-validation-error" id="validationSum">' + data.message + '</span>');

                }
                else {
                    $('.field-validation-error').remove(data.message);
                }
            },
        });
    });

    $('#create-submit').click(function () {
        debugger;
        var formcontainer = $('#form-container');
        var url = formcontainer.attr('data-url');
        var form = $('#create-form');
        form.removeData('validator');
        form.removeData('unobtrusiveValidation');
        $.validator.unobtrusive.parse(form);
        form.validationEngine('attach');

        return false;
    });

    $('.modal-title').html("<b>Create</b>");
</script>

Application.Web/Views/ExpectedReceipt/Delete.cshtml
@model Application.Web.Models.ViewModels.ExpectedReceiptViewModel.ExpectedReceipt
@{
    ViewBag.Title = "Expected Receipt Delete";
}

<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-ban"></i> Alert!</h4>
    Deleting this records cannot be undone. Are you sure you want to proceed?
</div>
<div class="box-body">
    <div class="col-md-12">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.GoodsReceivedNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GoodsReceivedNumber)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AutoReferenceNumber)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AutoReferenceNumber)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ReferenceNumber)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ReferenceNumber)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ExpectedReceiptDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ExpectedReceiptDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.WarehouseCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WarehouseCode)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Supplier)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Supplier)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.HaulierName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HaulierName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ReceivedDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ReceivedDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ReceivedBy)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ReceivedBy)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.StatusCode)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StatusCode)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Comments)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Comments)
            </dd>
            @*<dt>
                @Html.DisplayNameFor(model => model.Planned)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Planned)
            </dd>*@
        </dl>
    </div>
</div>

<div class="box-footer">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="submit" value="Delete" class="btn btn-danger pull-right" />
        @*| @Html.ActionLink("Back to List", "Index")*@
    }
</div>

<script type="text/javascript">

    $('.modal-title').html("<b>Delete</b>");

</script>

Application.Web/Views/ExpectedReceipt/Enable.cshtml
@model Application.Web.Models.ViewModels.ExpectedReceiptViewModel.ExpectedReceipt
@{
    ViewBag.Title = "Expected Receipt Enable";
}

<div class="alert alert-success alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-ban"></i> Alert!</h4>
    Are you sure you want to enable this record again?
</div>
<div class="box-body">
    <div class="col-md-12">
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.GoodsReceivedNumber)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.GoodsReceivedNumber)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.AutoReferenceNumber)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.AutoReferenceNumber)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ReferenceNumber)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ReferenceNumber)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ExpectedReceiptDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ExpectedReceiptDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.WarehouseCode)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.WarehouseCode)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Address)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Address)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Supplier)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Supplier)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.HaulierName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.HaulierName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ReceivedDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ReceivedDate)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.ReceivedBy)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.ReceivedBy)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.StatusCode)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.StatusCode)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Comments)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Comments)
            </dd>
            @*<dt>
                    @Html.DisplayNameFor(model => model.Planned)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Planned)
                </dd>*@
        </dl>
    </div>
</div>

<div class="box-footer">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <input type="submit" value="Enable" class="btn btn-primary pull-right" />
        @*| @Html.ActionLink("Back to List", "Index")*@
    }
</div>

<script type="text/javascript">

    $('.modal-title').html("<b>Enable</b>");

</script>