Application.Web/Controllers/Transaction/DeliveryRequestLineItemController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Application.Web.Models;
using Application.Web.Models.ViewModels;
using Application.Web.Helper;
using Newtonsoft.Json;
using RestSharp;

namespace Application.Web.Controllers.Transaction
{
    public class DeliveryRequestLineItemController : BaseController
    {


        // GET: DeliveryRequestLineItem
        [Authorize]
        public async Task<ActionResult> Index(long? id,long? deliveryRequestId, long? productId)
        {

            var list = new List<DeliveryRequestLineItemViewModel>();
            var url = "api/GoodsOut/CustomerDespatch/Line/Item/GetListByLineId/" + id;
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {
                var result = response.Content;
                var obj = JsonConvert.DeserializeObject<List<DeliveryRequestLineItemViewModel>>(result);
                list = obj;
            }

            if (response.IsSuccessful)
            {
                var result = response.Content;
                list = JsonConvert.DeserializeObject<List<dynamic>>(result).Select(x => new DeliveryRequestLineItemViewModel
                {
                    Id = x.Id,
                    DeliveryRequestLineId = x.DeliveryRequestLineId,
                    ItemId = x.ItemId,
                    ItemDescription = x.Item.Description,

                }).ToList();
            }
            ViewBag.ProductId = productId;
            ViewBag.DeliveryRequestLineId = id;
            ViewBag.DeliveryRequestId = deliveryRequestId;
            return View(list);
        }

        // GET: DeliveryRequestLineItem/Details/5
        [Authorize]
        public async Task<ActionResult> Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var obj = new DeliveryRequestLineItemViewModel();
            var url = "api/GoodsOut/CustomerDespatch/Line/Item/getbyid/" + id;
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {
                var result = response.Content;
                var data = JsonConvert.DeserializeObject<dynamic>(result);

                obj.Id = data.Id;
                obj.DeliveryRequestLineId = data.DeliveryRequestLineId;
                obj.ItemId = data.ItemId;
                obj.ItemDescription = data.Item.Description;

            }

            return PartialView(obj);
        }

        // GET: DeliveryRequestLineItem/Create
        [Authorize]
        public ActionResult Create(long? id,long? deliveryRequestId, long? productId)
        {
            var obj = new DeliveryRequestLineItemViewModel();
            obj.DeliveryRequestLineId = id;
            obj.ProductId = productId;
            obj.DeliveryRequestId = deliveryRequestId;
            return PartialView(obj);
        }

        // POST: DeliveryRequestLineItem/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,DeliveryRequestLineId,ItemId,ProductId,DeliveryRequestId")] DeliveryRequestLineItemViewModel deliveryRequestLineItemViewModel)
        {
            var url = "api/GoodsOut/CustomerDespatch/Line/Item/Add";

            var response = await HttpClientHelper.ApiCall(url, Method.POST, deliveryRequestLineItemViewModel);

            if (response.IsSuccessful)
            {
                TempData["Message"] = "Successfully Created";
                return RedirectToAction("Index", new { id = deliveryRequestLineItemViewModel.DeliveryRequestLineId, deliveryRequestLineItemViewModel.DeliveryRequestId, deliveryRequestLineItemViewModel.ProductId });
            }
            else
            {
                Error("An error has occurred");
                Log.Error(string.Format(Type.GetType(typeof(DeliveryRequestLineItemController).Name) + "||Create||DeliveryRequestLine ID::{0}||API Response::{1}", deliveryRequestLineItemViewModel.Id, response));
                return RedirectToAction("Index", new { id = deliveryRequestLineItemViewModel.DeliveryRequestLineId, deliveryRequestLineItemViewModel.DeliveryRequestId, deliveryRequestLineItemViewModel.ProductId });
            }
        }

        // GET: DeliveryRequestLineItem/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(long? id,long? deliveryRequestId, long? productId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var obj = new DeliveryRequestLineItemViewModel();
            var url = "api/GoodsOut/CustomerDespatch/Line/Item/getbyid/" + id;
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {
                var result = response.Content;
                var data = JsonConvert.DeserializeObject<dynamic>(result);

                obj.Id = data.Id;
                obj.DeliveryRequestLineId = data.DeliveryRequestLineId;
                obj.ItemId = data.ItemId;
                obj.ItemDescription = data.Item.Description;
                obj.ProductId = productId;
                obj.DeliveryRequestId = deliveryRequestId;
            }

            return PartialView(obj);
        }

        // POST: DeliveryRequestLineItem/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,DeliveryRequestLineId,ItemId,ProductId,DeliveryRequestId")] DeliveryRequestLineItemViewModel deliveryRequestLineItemViewModel)
        {
            var url = "api/GoodsOut/CustomerDespatch/Line/Item/update";
            var response = await HttpClientHelper.ApiCall(url, Method.PUT, deliveryRequestLineItemViewModel);

            if (response.IsSuccessful)
            {
                TempData["Message"] = "Successfully Updated";
                return RedirectToAction("Index", new { id = deliveryRequestLineItemViewModel.DeliveryRequestLineId, deliveryRequestLineItemViewModel.DeliveryRequestId, deliveryRequestLineItemViewModel.ProductId });
            }
            else
            {
                Error("An error has occurred");
                Log.Error(string.Format(Type.GetType(typeof(DeliveryRequestLineItemController).Name) + "||Update||DeliveryRequestLineItem ID::{0}||API Response::{1}", deliveryRequestLineItemViewModel.Id, response));
                return RedirectToAction("Index", new { id = deliveryRequestLineItemViewModel.DeliveryRequestLineId, deliveryRequestLineItemViewModel.DeliveryRequestId, deliveryRequestLineItemViewModel.ProductId });
            }
        }

        // GET: DeliveryRequestLineItem/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(long? id,long? deliveryRequestId, long? productId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var obj = new DeliveryRequestLineItemViewModel();
            var url = "api/GoodsOut/CustomerDespatch/Line/Item/getbyid/" + id;
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {
                var result = response.Content;
                var data = JsonConvert.DeserializeObject<dynamic>(result);

                obj.Id = data.Id;
                obj.DeliveryRequestLineId = data.DeliveryRequestLineId;
                obj.ItemId = data.ItemId;
                obj.ItemDescription = data.Item.Description;
                obj.ProductId = productId;
                obj.DeliveryRequestId = deliveryRequestId;
            }

            return PartialView(obj);
        }

        // POST: DeliveryRequestLineItem/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(long id, long? DeliveryRequestLineId, long? DeliveryRequestId,long? ProductId)
        {
            var url = "api/GoodsOut/CustomerDespatch/Line/Item/delete/" + id;

            var response = await HttpClientHelper.ApiCall(url, Method.DELETE);

            if (response.IsSuccessful)
            {
                TempData["Message"] = "Successfully Deleted";
                return RedirectToAction("Index",new { id = DeliveryRequestLineId, deliveryRequestId = DeliveryRequestId, productId = ProductId });
            }
            else
            {
                Error("An error has occurred");
                Log.Error(string.Format(Type.GetType(typeof(DeliveryRequestLineItemController).Name) + "||Delete||DeliveryRequestLineItem ID::{0}||API Response::{1}", id, response));
                return RedirectToAction("Index", new { id = DeliveryRequestLineId, deliveryRequestId = DeliveryRequestId, productId = ProductId });
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<JsonResult> ItemList(long productId ,string term)
        {
            var list = new List<ItemViewModel>();
            var url = "api/item/getselectlist/" + productId;
            var response = await HttpClientHelper.ApiCall(url, Method.GET);

            if (response.IsSuccessful)
            {

Application.Web/Views/DeliveryRequestLineItem/Create.cshtml
@model Application.Web.Models.ViewModels.DeliveryRequestLineItemViewModel


@{
    ViewBag.Title = "Create";
}

<div id="form-container" data-url="@Url.Action("Create","DeliveryRequestLineItem")">
    @using (Html.BeginForm("Create", "DeliveryRequestLineItem", FormMethod.Post, new { id = "create-form", enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductId)
        @Html.HiddenFor(model => model.DeliveryRequestLineId)
        @Html.HiddenFor(model => model.DeliveryRequestId)
        <div class="box-body">
            <div class="form-horizontal">
                <div class="col-md-12">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @*<div class="form-group">
                            @Html.LabelFor(model => model.DeliverRequestLineItemId, htmlAttributes: new { @class = "control-label col-md-3"  })
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.DeliverRequestLineItemId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DeliverRequestLineItemId, "", new { @class = "text-danger" })
                            </div>
                        </div>*@
                    <div class="form-group">
                        @Html.LabelFor(model => model.ItemId, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-12">
                            <select class="form-control" id="ItemId" name="ItemId">
                            </select>
                            @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @*<div class="form-group">
                            @Html.LabelFor(model => model.ItemId, "ItemId", htmlAttributes: new { @class = "control-label col-md-3"  })
                            <div class="col-md-12">
                                @Html.DropDownList("ItemId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
                            </div>
                        </div>*@



                    <div class="box-footer">
                        <input type="submit" id="create-submit" value="Save" class="btn btn-primary pull-right" />
                    </div>
                </div>
            </div>
        </div>
    }
</div>



<script type="text/javascript">

    $('#create-submit').click(function () {
        var formcontainer = $('#form-container');
        var url = formcontainer.attr('data-url');
        var form = $('#create-form');
        form.removeData('validator');
        form.removeData('unobtrusiveValidation');
        $.validator.unobtrusive.parse(form);
        form.validationEngine('validate');

        return false;
    });

    $('.modal-title').html("<b>Create</b>");

     $('#ItemId').select2({
        ajax: {
            url: '@Url.Action("ItemList", "DeliveryRequestLineItem")' + '?productId=' + '@Model.ProductId',
            type: "POST",
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    term: params.term,
                    q: params.term,// search term
                    page: params.page
                };
            },
            results: function (data) {

                return {
                    results: data

                };
            },

            processResults: function (data, params) {

                params.page = params.page || 1;

                return {
                    results: data,
                    pagination: {
                        more: (params.page * 30) < data.total_count
                    }
                };
            },

            cache: true
        },
        placeholder: 'Search',
        minimumInputLength: 3,
        width: '540',

    });

</script>

Application.Web/Views/DeliveryRequestLineItem/Delete.cshtml
@model Application.Web.Models.ViewModels.DeliveryRequestLineItemViewModel

@{
    ViewBag.Title = "Delete";
}
<div class="alert alert-danger alert-dismissible">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-ban"></i> Alert!</h4>
    Deleting this records cannot be undone. Are you sure you want to proceed?
</div>
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDescription)
        </dd>

    </dl>

    @using (Html.BeginForm())
            {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.DeliveryRequestLineId)
        @Html.HiddenFor(model => model.ProductId)
        @Html.HiddenFor(model => model.DeliveryRequestId)
        <div class="box-footer">
            <input type="submit" value="Delete" class="btn btn-primary pull-right" />
        </div>
    }
</div>


<script type="text/javascript">
    $('.modal-title').html("<b>Delete</b>");
</script>

Application.Web/Views/DeliveryRequestLineItem/Details.cshtml
@model Application.Web.Models.ViewModels.DeliveryRequestLineItemViewModel

@{
    ViewBag.Title = "Details";
}

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDescription)
        </dd>
    </dl>
    <div class="box-footer">
        <button type="button" class="btn btn-primary pull-right crud" data-id="@Model.Id" data-request-url="@Url.Action("Edit")">Edit</button>
    </div>
</div>

<script type="text/javascript">

    $(".crud").click(function () {

        debugger;
        var btnClick = $(this);
        var url = btnClick.data('request-url') + '?id=' + btnClick.data('id');
        AjaxCrudCall(url, "GET");
    });

    $('.modal-title').html("<b>Details</b>");

</script>

Application.Web/Views/DeliveryRequestLineItem/Edit.cshtml
@model Application.Web.Models.ViewModels.DeliveryRequestLineItemViewModel

@{
    ViewBag.Title = "Edit";
}
<div id="form-container" data-url="@Url.Action("Edit","DeliveryRequestLineItem")">
    @using (Html.BeginForm("Edit", "DeliveryRequestLineItem", FormMethod.Post, new { id = "edit-form", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="box-body">
            <div class="form-horizontal">
                <div class="col-md-12">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.ProductId)
                    @Html.HiddenFor(model => model.DeliveryRequestLineId)
                    @Html.HiddenFor(model => model.DeliveryRequestId)

                    @*<div class="form-group">
                            @Html.LabelFor(model => model.DeliverRequestLineItemId, htmlAttributes: new { @class = "control-label col-md-3"  })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.DeliverRequestLineItemId, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.DeliverRequestLineItemId, "", new { @class = "text-danger" })
                            </div>
                        </div>*@
                    <div class="form-group">
                        @Html.LabelFor(model => model.ItemId, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-10">
                            <select class="form-control" id="ItemId" name="ItemId">
                                <option value="ItemId" selected="selected">@Model.ItemDescription</option>
                            </select>
                            @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @*<div class="form-group">
                            @Html.LabelFor(model => model.ItemId, "ItemId", htmlAttributes: new { @class = "control-label col-md-3"  })
                            <div class="col-md-10">
                                @Html.DropDownList("ItemId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.ItemId, "", new { @class = "text-danger" })
                            </div>
                        </div>*@



                    <div class="box-footer">
                        <input type="submit" id="edit-submit" value="Save" class="btn btn-primary pull-right" />
                    </div>
                </div>
            </div>
        </div>
    }
</div>



<script type="text/javascript">

    $('#edit-submit').click(function () {
        var formcontainer = $('#form-container');
        var url = formcontainer.attr('data-url');
        var form = $('#edit-form');
        form.removeData('validator');
        form.removeData('unobtrusiveValidation');
        $.validator.unobtrusive.parse(form);
        form.validationEngine('validate');

        return false;
    });

    $('.modal-title').html("<b>Edit</b>");

    $('#ItemId').select2({
        ajax: {
            url: '@Url.Action("ItemList", "DeliveryRequestLineItem")' + '?productId=' + '@Model.ProductId' ,
            type: "POST",
            dataType: 'json',
            delay: 250,
            data: function (params) {
                return {
                    term: params.term,
                    q: params.term,// search term
                    page: params.page
                };
            },
            results: function (data) {

                return {
                    results: data

                };
            },

            processResults: function (data, params) {

                params.page = params.page || 1;

                return {
                    results: data,
                    pagination: {
                        more: (params.page * 30) < data.total_count
                    }
                };
            },

            cache: true
        },
        placeholder: 'Search',
        minimumInputLength: 3,
        width: '540',

    });
</script>

Application.Web/Views/DeliveryRequestLineItem/Index.cshtml
@model IEnumerable<Application.Web.Models.ViewModels.DeliveryRequestLineItemViewModel>

@{
    ViewBag.Title = "Delivery Request Line Item Listing";
}
<p>
    <button id="createBtn" type="button" class="btn btn-primary crud" data-id="@ViewBag.DeliveryRequestLineId" data-request-url="@Url.Action("Create","DeliveryRequestLineItem")">Create</button>
    @*<a href="@Url.Action("Index","DeliveryRequestLine", new { id = @ViewBag.DeliveryRequestId } )">Back To List</a>*@
    @Html.ActionLink("Back to list", "Index", new {Controller = "DeliveryRequestLine", id = @ViewBag.DeliveryRequestId } , new { @class = "btn btn-primary btn-large" })
</p>

@Html.Partial("_CrudModal")
<div class="table-responsive">
    <div class="box-body">
        <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
            <table id="dataTable" class="table table-bordered table-striped dataTable" role="grid" aria-describedby="datatable_info">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ItemDescription)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ItemDescription)
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="#"><i class="fa fa-gear fa-fw"></i> Action</a>
                                    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
                                        <span class="fa fa-caret-down" title="Toggle dropdown menu"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li class="crud" data-id="@item.Id" data-product-id="@ViewBag.ProductId" data-request-url="@Url.Action("Edit")"><a>Edit</a></li>
                                        <li class="crud" data-id="@item.Id" data-product-id="@ViewBag.ProductId" data-request-url="@Url.Action("Details")"><a>Details</a></li>
                                        <li class="crud" data-id="@item.Id" data-product-id="@ViewBag.ProductId" data-request-url="@Url.Action("Delete")"><a>Delete</a></li>

                                    </ul>
                                </div>
                            </td>
                        </tr>
                    }
                    </tbody>
            </table>
        </div>
    </div>
</div>

<script type="text/javascript">

     var msg = "@TempData["Message"]";
    if (msg != "") {
        swal("Success!", "@TempData["Message"]".toString(), "success");
        '@TempData.Remove("Message")';
    }

    $("#dataTable").DataTable();

    $("#dataTable").on("click", ".crud", function () {
        btnClicked($(this));
    });

    $("#createBtn").click(function () {
        btnClicked($(this));
    });

    var btnClicked = function (btnClick) {

        var url = "";

        if (btnClick.data('target') == "Delete") {
             url = btnClick.data('request-url') + '?id=' + btnClick.data('id')+ '&deliveryRequestId=' +  '@ViewBag.DeliveryRequestId' + '&productId=' +  '@ViewBag.ProductId';
        }
        else {
            url = btnClick.data('request-url') + '?id=' + btnClick.data('id') + '&deliveryRequestId=' +  '@ViewBag.DeliveryRequestId' + '&productId=' +  '@ViewBag.ProductId';
        }

        AjaxCrudCall(url, "GET");


    };

</script>